<?php 
// Check that the nonce is valid, and the user can edit this post.

	if ( ! function_exists( 'wp_handle_upload' ) ) {
	    require_once( ABSPATH . 'wp-admin/includes/file.php' );
	}
	$uploadedfile = $_FILES['fileToUpload'];
	$upload_overrides = array( 'test_form' => false );
	$movefile = wp_handle_upload( $uploadedfile, $upload_overrides );
	if ( $movefile && ! isset( $movefile['error'] ) ) {
			if(!file_exists(wp_upload_dir()['basedir'] . '/student_sorter_uploads'.'/'.$_FILES['fileToUpload']['name'])){
			//Get unzip function from wordpress
			require_once(ABSPATH .'/wp-admin/includes/file.php');
			global $wp_filesystem;
			if ( ! $filesystem ) { WP_Filesystem(); if ( ! $wp_filesystem ){ print_r('wp_filesystem no found'); } }
			//store long vars
			$old_dir = $movefile['file'];
			$new_dir = wp_upload_dir()['basedir'] . '/student_sorter_uploads'.'/'.$_FILES['fileToUpload']['name'];
			$clean_name = explode('.zip',$_FILES['fileToUpload']['name'])[0];
			$folder_dir = wp_upload_dir()['basedir'] . '/student_sorter_uploads'.'/'.$clean_name;

			/*=================================
			=            Move File            =
			=================================*/
			rename($old_dir, $new_dir);
			/*==================================
			=            Unzip file            =
			==================================*/
			//Unzip to folder called clean name - store the result 1 or 0 for error checking.
			$result = unzip_file( $new_dir, $folder_dir);
			print_r($result);
			if ( is_wp_error( $result ) ){
					print_r(is_wp_error( $result ));
			} 
			/*========================================
			=            Store File Names            =
			========================================*/
			$store['zips'][$clean_name] = $folder_dir;

			print_r($store['zips']);
			} else {
				echo 'Already a file there';
			}
			
	} else {
	    /**
	     * Error generated by _wp_handle_upload()
	     * @see _wp_handle_upload() in wp-admin/includes/file.php
	     */
	    // echo $movefile['error'];
	}

	// The security check failed, maybe show the user an error.




?>