<?php 
// Check that the nonce is valid, and the user can edit this post.
	
	$submit = $_POST['submit'];

switch ($submit) {
	case 'Sort Photo':
		if ( ! function_exists( 'wp_handle_upload' ) ) {
	    require_once( ABSPATH . 'wp-admin/includes/file.php' );
	}
	$uploadedfile = $_FILES['fileToUpload'];
	
	$uploadedFilePath = wp_upload_dir()['basedir'] . '/student_sorter_uploads'.'/'.$uploadedfile['name'];

	$upload_overrides = array( 'test_form' => false );
	$movefile = wp_handle_upload( $uploadedfile, $upload_overrides );
	if ( $movefile && ! isset( $movefile['error'] ) ) {
			/*If Zip doesn't exists*/
			if(!file_exists($uploadedFilePath)){
			//Get unzip function from wordpress
			 require_once(ABSPATH .'wp-admin/includes/file.php');
		
			WP_Filesystem(); 
			echo "File doesnt exist </br>";
			//store long vars
			$old_dir = $movefile['file'];
			//echo "Old dir: ".$old_dir."</br>";
			$new_dir = wp_upload_dir()['basedir'] . '/student_sorter_uploads'.'/'.$uploadedfile['name'];
			echo "New dir: ".$new_dir."</br>";
			$clean_name = explode('.zip',$uploadedfile['name'])[0];
			$folder_dir = wp_upload_dir()['basedir'] . '/student_sorter_uploads'.'/'.$clean_name;
			$_SESSION["folder_dir"] = $folder_dir;
			echo "base dir: ".wp_upload_dir()['basedir']."</br>";
			/*=================================
			=            Move File            =
			=================================*/
			rename($old_dir, $new_dir);
			/*==================================
			=            Unzip file            =
			==================================*/
			//Unzip to folder called clean name - store the result 1 or 0 for error checking.
			if (!file_exists($folder_dir)) {
	    	// echo "Folder doesnt exist: ".$folder_dir."</br>";
	    	wp_mkdir_p($folder_dir, 0777, true);
	    	// wp_mkdir_p($folder_dir."_thumb", 0777, true);
	    	// echo "creo: ".$x."</br>" ;
			}

			$zip = new ZipArchive;
			$res = $zip->open($new_dir);
			if ($res === TRUE) {
			  // extract it to the path we determined above
			  $zip->extractTo($folder_dir);
			  $zip->close();
			  // echo "WOOT! $new_dir extracted to $folder_dir";
			} else {
			  // echo "Doh! I couldn't open $new_dir";
			}	
		
			/*========================================
			=            Store File Names            =
			========================================*/
			$store['zips'][$clean_name] = $folder_dir;

			print_r($store['zips']);

			$files = glob($folder_dir."/*.*");

			$schools_shots = array();
			$student_session = array();
			$session = array();

			$current_student="";
			$count=0;

			$last=sizeof($files)-1;

			foreach ($files as $key=>$file) {
			  $qrcode = new QrReader($file);
			  if (!empty($qrcode->text())) {

			    
			    if ($count===0){
			      
			      $id = $qrcode->text();
			      
			      $count++;  
			    }else {
			      $student_session[$id] = $session;
			      $session = array();
			      $id = $qrcode->text();
			      $count++;
			    }
			    
			  }else{
			  	$photo_path= explode(wp_upload_dir()['basedir'], $file)[1];
			    if($photo_count === 0){
			    	
			    }
			    $session[] = array('checked' => false, 'file' => $photo_path);
			  }
			  if ($key===$last){
			    $student_session[$id] = $session;
			  }
			}

			$schools_shots = $student_session;

			$fp = fopen($folder_dir.'.json', 'w');
			fwrite($fp, json_encode($schools_shots));
			fclose($fp);

	} else {
		//print_r($uploadedfile);
		echo 'Already a file there '.$uploadedfile['name'];
		$clean_name = explode('.zip',$uploadedfile['name'])[0];
		$folder_dir = wp_upload_dir()['basedir'] . '/student_sorter_uploads'.'/'.$clean_name;
		$_SESSION["folder_dir"] = $folder_dir;
	}
			
	} else {
	    /**
	     * Error generated by _wp_handle_upload()
	     * @see _wp_handle_upload() in wp-admin/includes/file.php
	     */
	    // echo $movefile['error'];
	}

	// The security check failed, maybe show the user an error.
		break;
	
	case "Load": 
		$folder_dir = $_POST['load'];
		$_SESSION["folder_dir"] = $folder_dir;

		break;

	default:
		# code...
		break;
}

	




?>

